server:
  port: 8090
#  servlet:
#    context-path: /api/v1

spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/animalbrokers
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update

animalbrokers:
  app:
    jwtSecret: s3cr3tan1malbr0k3rs
    jwtExpirationMs: 8640000